name: Nairobi Real Estate Pipeline Continous Integration(CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nrbproperties
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Environment
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "Runner Image: $ImageOS"
        echo "Available Python versions:"
        ls /opt/hostedtoolcache/Python || echo "Python versions not found in default path"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Confirm Python version
      run: python --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Lint Python scripts with flake8
      run: |
        flake8 \
          --ignore=E302,E401,E402,E501,E702,E722,F401,W391,W292 \
          scraper/ \
          kafka_producer/producer/ \
          airflow_dags/dags/ \
          spark/ \
          notification/ \
          monitoring/

    - name: Run tests 
      run: |
        echo "No tests directory yet — skipping pytest"
        # pytest tests/

    - name: 🐳 Validate docker compose syntax
      run: |
        docker compose -f docker-compose.yml config
